-- 第一题
SELECT *
FROM EMP
WHERE EMP.COMM > EMP.SAL * 0.6

-- 第二题
SELECT *
FROM EMP
WHERE LENGTH(EMP.ENAME) = 6

-- 第三题
SELECT *
FROM EMP
WHERE locate('R', EMP.ENAME) = 0;

-- 第四题
SELECT A.ENAME  AS 'EMPLOYEE',
       B.ENAME  AS 'MANAGER_NAME',
       B.DEPTNO AS 'DEPTNO'
FROM EMP A,
     EMP B
WHERE A.HIREDATE < B.HIREDATE
  AND B.JOB = 'MANAGER'
  AND A.DEPTNO = B.DEPTNO

-- 第五题
SELECT DEPT.DEPTNO,
       DEPT.DNAME,
       DEPT.LOC,
       COUNT(EMP.ENAME) AS '人数'
FROM EMP,
     DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO
GROUP BY DEPT.DEPTNO

-- 第六题
SELECT ENAME,
       EMP.SAL * 12 AS 'SALARY'
FROM EMP
ORDER BY EMP.SAL * 12 DESC

